dbt_project:
  outputs:
    prod:
      account: kba63133
      database: DEMO_DB
      password: Mahakal@1
      role: GLOBAL_DATA_ENGINEER_FR
      schema: DYNAMO_DB_DATA_DBT
      threads: 1
      type: snowflake
      user: Abhishek.Shrivastava
      warehouse: GLOBAL_DATA_ENGINEER_WH
  target: dev
my-snowflake-db:
  outputs:
    dev:
      account: kba63133
      client_session_keep_alive: false
      connect_retries: 0
      connect_timeout: 10
      database: GLOBAL_LOAD_DB
      password: Mahakal@1
      retry_all: false
      retry_on_database_errors: false
      role: GLOBAL_DATA_ENGINEER_FR
      schema: TRANSFORMED_DYNAMO_SCMA
      threads: 2
      type: snowflake
      user: Abhishek.Shrivastava
      warehouse: GLOBAL_DATA_ENGINEER_WH
  target: dev
